name: CI_release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Back-End repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: True

      - name: Install dependencies
        run: dotnet restore --interactive
        working-directory: Fragments-back-end

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: Fragments-back-end/Fragments.WebApi

      - name: Test
        run: dotnet test --no-restore --verbosity detailed
        working-directory: Fragments-back-end/Fragments.Test


  sonarcloud_analysis:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Back-End repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarScanner for .NET 6 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@v2.1.3
        with:
          sonarProjectKey: ita-social-projects_Fragments-back-end
          sonarProjectName:  Fragments-back-end
          sonarOrganization: ita-social-projects
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="/github/workspace/Fragments-back-end/Fragments.Test/coverage.opencover.xml" /d:sonar.coverage.exclusions=**/Fragments.Data/**,**/Fragments.Domain/Dto/**,**/Fragments.Domain/Extensions/**,**/Program.cs /d:sonar.exclusions=**/Fragments.Data/Migrations/**
          dotnetBuildArguments: ./Fragments-back-end/Fragments-back-end.sln -c Debug
          dotnetTestArguments: ./Fragments-back-end/Fragments.Test/Fragments.Test.csproj --no-restore --verbosity detailed /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
