name: CI_Pipeline
on:
  push:
    branches:
      - master
      - DevOps-9-implement-ci-for-fragments-back-end
  pull_request:
    branches:
    - master
env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Back-End repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          packageType: 'sdk'
          dotnet-version: |
            5.0.x
            6.0.x
          include-prerelease: True

      - name: Install dependencies
        run: dotnet restore --interactive
        working-directory: Fragments-back-end

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: Fragments-back-end/Fragments.WebApi

      - name: Test
        run: dotnet test --no-restore -v n
        working-directory: Fragments-back-end/Fragments.Test


  sonarscan:
    needs: [build_and_test]
    runs-on: ubuntu-latest

    steps:
    - name: Clone Back-End repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # .net 5 version
    # - name: SonarScanner for .NET 5 with pull request decoration support
    #   uses: highbyte/sonarscan-dotnet@2.0
    #   #uncoment the line above and comment the line below when NuGet will fix their issues
    #   #uses: SplinterRAT/sonarscan-dotnet@v2.0.0.1
    #   with:
    #     sonarProjectKey: ita-social-projects_Fragments-back-end
    #     sonarProjectName:  Fragments-back-end
    #     sonarOrganization: ita-social-projects
    #     sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="/github/workspace/Fragments-back-end/Fragments.Test/coverage.opencover.xml" /d:sonar.coverage.exclusions=**/Fragments.Data/**,**/Fragments.Domain/Dto/**,**/Fragments.Domain/Extensions/**,**/Program.cs /d:sonar.exclusions=**/Fragments.Data/Migrations/**
    #     dotnetBuildArguments: ./Fragments-back-end/Fragments-back-end.sln -c Debug
    #     dotnetTestArguments: ./Fragments-back-end/Fragments.Test/Fragments.Test.csproj --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: SonarScanner for .NET 6 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@2.1.3
      with:
        sonarProjectKey: ita-social-projects_Fragments-back-end
        sonarProjectName:  Fragments-back-end
        sonarOrganization: ita-social-projects
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="/github/workspace/Fragments-back-end/Fragments.Test/coverage.opencover.xml" /d:sonar.coverage.exclusions=**/Fragments.Data/**,**/Fragments.Domain/Dto/**,**/Fragments.Domain/Extensions/**,**/Program.cs /d:sonar.exclusions=**/Fragments.Data/Migrations/**
        dotnetBuildArguments: ./Fragments-back-end/Fragments-back-end.sln -c Debug
        dotnetTestArguments: ./Fragments-back-end/Fragments.Test/Fragments.Test.csproj --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
