name: CI_Pipeline
on:
  push:
    branches: [ DevOps-9-implement-ci-for-fragments-back-end ]
#  pull_request:
#    branches: [ master ]
env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Back-End repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          packageType: 'sdk'
          dotnet-version: |
            5.0.x
            6.0.x
          include-prerelease: True

      - name: Install dependencies
        run: dotnet restore --interactive
        working-directory: Fragments-back-end

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: Fragments-back-end/Fragments.WebApi

      - name: Test
        run: dotnet test --no-restore -v n
        working-directory: Fragments-back-end/Fragments.Test
